# Generated by Django 4.0.3 on 2022-04-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('mobile_operator', models.CharField(blank=True, max_length=40, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=70, null=True)),
                ('dish_operator', models.CharField(blank=True, max_length=70, null=True)),
                ('electricity', models.CharField(blank=True, max_length=70, null=True)),
                ('electricity_operator', models.CharField(blank=True, max_length=70, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('Recharge_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('recharge_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
