# Generated by Django 4.0.3 on 2022-04-26 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_num', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=70, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('recharge_status', models.CharField(blank=True, max_length=70, null=True)),
                ('error_message', models.CharField(blank=True, max_length=70, null=True)),
                ('transition_id', models.CharField(blank=True, max_length=70, null=True)),
                ('history_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
