# Generated by Django 4.0.3 on 2022-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0002_rechargehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargehistory',
            name='acc_num',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
