# Generated by Django 4.0.3 on 2022-04-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField()),
                ('transition_id', models.CharField(blank=True, max_length=70, null=True)),
                ('order_id', models.CharField(blank=True, max_length=70, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_get_or_send', models.CharField(max_length=40, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard_front', models.ImageField(blank=True, null=True, upload_to='document/pancard')),
                ('adharcard_front', models.ImageField(blank=True, null=True, upload_to='document/adharcard')),
                ('adharcard_backside', models.ImageField(blank=True, null=True, upload_to='document/adharcard')),
                ('user_signature', models.ImageField(blank=True, null=True, upload_to='document/signature')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pancard', models.CharField(blank=True, max_length=80, null=True)),
                ('adharcard', models.CharField(blank=True, max_length=80, null=True)),
                ('account', models.IntegerField(blank=True, null=True)),
                ('account_verify', models.IntegerField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
