# Generated by Django 4.0.3 on 2022-04-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd_owner', models.CharField(max_length=70, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('address1', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('mobile', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=70, null=True)),
                ('payment_id', models.CharField(max_length=70, null=True)),
                ('payment_status', models.BooleanField(default=True)),
                ('duration', models.CharField(max_length=70, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
